@startuml flush_and_submit

main -> GrDirectContext : flushAndSubmit(sync)
activate GrDirectContext

GrDirectContext -> GrDirectContext : flush(info)
activate GrDirectContext

GrDirectContext -> GrDrawingManager : flushSurfaces({}, kNoAccess, info, null)
activate GrDrawingManager

GrDrawingManager -> GrDrawingManager : flush({}, kNoAccess, info, null)
activate GrDrawingManager

GrDrawingManager -> GrDrawingManager : executeRenderTasks(flushstate)
activate GrDrawingManager

GrDrawingManager -> GrRenderTask : execute(flushState)
activate GrRenderTask

GrRenderTask -> OpsTask : onExecute(flushState)
activate OpsTask

OpsTask -> GrOp : execute(flushState,chainBounds)
activate GrOp

GrOp -> FillRRectOpImpl : onExecute(flushState,chainBounds)
activate FillRRectOpImpl

FillRRectOpImpl -> GrOpFlushState : bindPipelineAndScissorClip(programInfo,chainBounds)
activate GrOpFlushState

GrOpFlushState -> GrOpFlushState : bindPipeline(programInfo,chainBounds)
activate GrOpFlushState

GrOpFlushState -> GrOpsRenderPass : bindPipeline(programInfo,chainBounds)
activate GrOpsRenderPass

GrOpsRenderPass -> GrGLOpsRenderPass : onBindPipeline(programInfo,chainBounds)
activate GrGLOpsRenderPass

GrGLOpsRenderPass -> GrGLGpu : flushGLState(fRenderTarget,bool,programInfo)
activate GrGLGpu

GrGLGpu -> ProgramCache : findOrCreateProgramInfo(dContextr,programInfo)
activate ProgramCache

ProgramCache -> GrGLCaps : makeDesc(null,programInfo)
activate GrGLCaps

GrGLCaps -> GrProgramDesc : Build(desc,programInfo,this)
activate GrProgramDesc

GrProgramDesc -> GrProgramDesc : gen_key()
activate GrProgramDesc

GrProgramDesc -> GrGLCaps : return desc
deactivate GrProgramDesc
deactivate GrProgramDesc

GrGLCaps -> ProgramCache : return desc
deactivate GrGLCaps

ProgramCache -> ProgramCache : findOrCreateProgramImpl(dContextr,primInfo,stat)
activate ProgramCache

ProgramCache -> GrGLProgramBuilder : CreateProgram(dContext,desc,programInfo)
activate GrGLProgramBuilder

GrGLProgramBuilder -> GrGLProgramBuilder : finalize(null)
activate GrGLProgramBuilder

GrGLProgramBuilder -> opengl : glCreateProgram()
activate opengl
opengl -> GrGLProgramBuilder : return programID
deactivate opengl

GrGLProgramBuilder -> opengl : glProgramParameteri(..)
activate opengl
note right
这里需要告知gpu 驱动，需要获取编译后
的二进制数据
end note

opengl -> GrGLProgramBuilder : return
deactivate opengl

GrGLProgramBuilder -> GrGLSLProgramBuilder : finalizeShaders()
activate GrGLSLProgramBuilder

GrGLSLProgramBuilder -> GrGLSLShaderBuilder : finalize(kVertex_GrShaderFlag)
activate GrGLSLShaderBuilder

GrGLSLShaderBuilder -> GrGLSLVertexBuilder : onFinalize()
activate GrGLSLVertexBuilder

GrGLSLVertexBuilder -> GrGLSLShaderBuilder : return
deactivate GrGLSLVertexBuilder

GrGLSLShaderBuilder -> GrGLSLProgramBuilder : return
deactivate GrGLSLShaderBuilder

GrGLSLProgramBuilder -> GrGLSLShaderBuilder : finalize(kFragment_GrShaderFlag)
activate GrGLSLShaderBuilder

GrGLSLShaderBuilder -> GrGLSLFragmentShaderBuilder : onFinalize()
activate GrGLSLFragmentShaderBuilder

GrGLSLFragmentShaderBuilder -> GrGLSLShaderBuilder : return
deactivate GrGLSLFragmentShaderBuilder

GrGLSLShaderBuilder -> GrGLSLProgramBuilder : return
deactivate GrGLSLShaderBuilder

GrGLSLProgramBuilder -> GrGLProgramBuilder : return
deactivate GrGLSLProgramBuilder

GrGLProgramBuilder -> skgpu : SkSLToGLSL(..)
activate skgpu
note right
先编译 fragment shader 
有两个参数，glsl数组和 sksl数组，存放
vertex shader 和 fragment shader
end note

skgpu -> skgpu : SkSLToBackend(..)
activate skgpu
note right
在这里,sksl转换为glsl
end note

skgpu -> GrGLProgramBuilder : return
deactivate skgpu
deactivate skgpu

GrGLProgramBuilder -> GrGLProgramBuilder : compileAndAttachShaders(..)
activate GrGLProgramBuilder

GrGLProgramBuilder -> GrGLShaderStringBuilder : GrGLCompileAndAttachShader(..)
activate GrGLShaderStringBuilder

GrGLShaderStringBuilder -> opengl : glCreateShader(type)
activate opengl

opengl -> GrGLShaderStringBuilder : return shaderID
deactivate opengl

GrGLShaderStringBuilder -> opengl : glShaderSource(shaderID,..)
activate opengl

opengl -> GrGLShaderStringBuilder : return
deactivate opengl

GrGLShaderStringBuilder -> opengl : glCompileShader(shaderID)
activate opengl

opengl -> GrGLShaderStringBuilder : return
deactivate opengl

GrGLShaderStringBuilder -> GrGLProgramBuilder : return
deactivate GrGLShaderStringBuilder
note right
完成对fragment shader的编译
end note
deactivate GrGLProgramBuilder
note left
vertex shader 编译流程和fragment shader
一样,不再赘述
end note

GrGLProgramBuilder -> opengl : glLinkProgram(programID)
activate opengl

opengl -> GrGLProgramBuilder : return
deactivate opengl

GrGLProgramBuilder -> GrGLProgramBuilder : storeShaderInCache(..)
activate GrGLProgramBuilder
note right
通过 PersistentCache
保存编译后的二进制产物。PerssistentCache
提供了 store() 函数接口，传入 key 和 data
持久性存储到本地文件中。
end note

GrGLProgramBuilder -> opengl : glGetProgramBinary(programID,..)
activate opengl

opengl -> GrGLProgramBuilder : return
deactivate opengl
@enduml